export const DOCUMENT_TYPES = [
  "Cédula de habitabilidad",
  "Certificado energético",
  "Contrato de arrendamiento",
  "Documento identificación propietario",
  "Escrituras",
  "Licencia de primera ocupación",
  "Nota simple",
  "Certificado de estar al corriente con la comunidad",
  "Último recibo de IBI",
  "Referencia catastral / Certificado catastral descriptivo y gráfico",
  "Recibos de suministros recientes",
  "Certificado de deuda cero hipotecaria",
  "Escritura de cancelación de hipoteca",
  "Estatutos de la comunidad de propietarios",
  "Actas recientes de la comunidad (últimos 1–2 años)",
  "Informe ITE / IEE (según antigüedad del edificio)",
  "Seguro del hogar (póliza)",
  "Inventario firmado (en alquiler amueblado)",
  "Acta de entrega de llaves",
  "Acta de estado del inmueble (check-in / check-out)",
  "Certificado de instalación eléctrica (boletín)",
  "Certificado de instalación de gas",
  "Licencia turística (si aplica)",
  "Número de registro de alquiler turístico",
  "Contrato de arras (en venta)",
  "Contrato de reserva",
  "Nota de encargo con la agencia",
  "Poder notarial (si firma un representante)",
  "Certificado de eficiencia energética registrado (no solo el informe)",
  "Planos del inmueble",
  "Memoria de calidades",
  "Proyecto técnico y licencia de obras (si hubo reforma relevante)",
  "Certificado final de obra",
  "Seguro decenal (en obra nueva)",
  "Libro del edificio (si aplica)",
  "Certificado de no afección urbanística",
  "Copia del DNI/NIE del inquilino",
  "Aval bancario o póliza de seguro de impago",
  "Justificante de depósito de fianza en organismo autonómico",
] as const;
